[env]
WINIT_X11_SCALE_FACTOR = "1"

[colors.bright]
black = "0xa6accd"
blue = "0xadd7ff"
cyan = "0x89ddff"
green = "0x5de4c7"
magenta = "0xfae4fc"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x1b1e28"
blue = "#435c89"
cyan = "0xadd7ff"
green = "0x5de4c7"
magenta = "0xfcc5e9"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

[colors.primary]
background = "0x131621"
foreground = "0xa6accd"

[colors.search.matches]
background = "0xadd7ff"
foreground = "0x1b1e28"

[colors.selection]
background = "0x303340"
text = "CellForeground"

[cursor]
blink_interval = 750
style = "Beam"
thickness = 0.2
unfocused_hollow = false

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
y = 0

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
y = 0

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
mods = "Control"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.4
startup_mode = "Windowed"
title = "Alacritty Terminal"

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 24
y = 24
